// **** File generated by ase2next ***
// **** Do not edit ***

#ifndef _FRAMEDEFS_H_
#define _FRAMEDEFS_H_

#include "unified_sprites.h"

extern const FrameDefinition sprite_ball_shadow;
extern const FrameDefinition sprite_ball;
extern const FrameDefinition sprite_net;
extern const FrameDefinition sprite_player_back_a_00;
extern const FrameDefinition sprite_player_back_a_01;
extern const FrameDefinition sprite_umpire_head_00;
extern const FrameDefinition sprite_umpire_head_01;
extern const FrameDefinition sprite_umpire_head_02;
extern const FrameDefinition sprite_umpire_head_03;
extern const FrameDefinition sprite_player_back_a_02;
extern const FrameDefinition sprite_player_back_a_03;
extern const FrameDefinition sprite_player_back_a_04;
extern const FrameDefinition sprite_player_back_a_05;
extern const FrameDefinition sprite_player_back_a_06;
extern const FrameDefinition sprite_player_back_a_07;
extern const FrameDefinition sprite_player_back_a_08;
extern const FrameDefinition sprite_player_back_a_09;
extern const FrameDefinition sprite_player_back_a_10;
extern const FrameDefinition sprite_player_back_a_12;
extern const FrameDefinition sprite_player_back_a_11;
extern const FrameDefinition sprite_player_back_a_13;
extern const FrameDefinition sprite_player_back_a_14;
extern const FrameDefinition sprite_player_back_a_15;
extern const FrameDefinition sprite_player_front_a_01;
extern const FrameDefinition sprite_player_back_a_16;
extern const FrameDefinition sprite_player_back_a_17;
extern const FrameDefinition sprite_player_back_a_18;
extern const FrameDefinition sprite_player_back_a_19;
extern const FrameDefinition sprite_player_back_a_20;
extern const FrameDefinition sprite_player_front_a_00;
extern const FrameDefinition sprite_player_front_a_02;
extern const FrameDefinition sprite_player_front_a_03;
extern const FrameDefinition sprite_player_front_a_04;
extern const FrameDefinition sprite_player_front_a_11;
extern const FrameDefinition sprite_player_front_a_05;
extern const FrameDefinition sprite_player_front_a_06;
extern const FrameDefinition sprite_player_front_a_07;
extern const FrameDefinition sprite_player_front_a_08;
extern const FrameDefinition sprite_player_front_a_09;
extern const FrameDefinition sprite_player_front_a_10;
extern const FrameDefinition sprite_player_front_a_12;
extern const FrameDefinition sprite_player_front_a_13;
extern const FrameDefinition sprite_player_front_a_14;
extern const FrameDefinition sprite_player_front_a_15;
extern const FrameDefinition sprite_player_front_a_16;
extern const FrameDefinition sprite_player_front_a_17;
extern const FrameDefinition sprite_player_front_a_18;
extern const FrameDefinition sprite_player_front_a_19;
extern const FrameDefinition sprite_player_front_a_20;
extern const FrameDefinition sprite_umpire_chair;

#endif
