// File generated by layer2_screens.py
// Do not edit this file

#ifndef _LAYER2_SCREENS_H_
#define _LAYER2_SCREENS_H_

#define LY2_COURT_LONDON_PAGE 70
#define LY2_COURT_LONDON_ADDRESS (const void *)0xC000
#define LY2_COURT_LONDON LY2_COURT_LONDON_PAGE, LY2_COURT_LONDON_ADDRESS
extern const void* ly2_court_london;

#define LY2_COURT_MADRID_PAGE 71
#define LY2_COURT_MADRID_ADDRESS (const void *)0xCFB1
#define LY2_COURT_MADRID LY2_COURT_MADRID_PAGE, LY2_COURT_MADRID_ADDRESS
extern const void* ly2_court_madrid;

#define LY2_COURT_SIDNEY_PAGE 72
#define LY2_COURT_SIDNEY_ADDRESS (const void *)0xDB12
#define LY2_COURT_SIDNEY LY2_COURT_SIDNEY_PAGE, LY2_COURT_SIDNEY_ADDRESS
extern const void* ly2_court_sidney;

#define LY2_INTRO_SCREEN_PAGE 74
#define LY2_INTRO_SCREEN_ADDRESS (const void *)0xC65B
#define LY2_INTRO_SCREEN LY2_INTRO_SCREEN_PAGE, LY2_INTRO_SCREEN_ADDRESS
extern const void* ly2_intro_screen;

#define LY2_PLAYER_SELECTION_PAGE 76
#define LY2_PLAYER_SELECTION_ADDRESS (const void *)0xCE8A
#define LY2_PLAYER_SELECTION LY2_PLAYER_SELECTION_PAGE, LY2_PLAYER_SELECTION_ADDRESS
extern const void* ly2_player_selection;


#endif
