; File generated by layer2_screens.py
; Do not edit this file

PUBLIC _ly2_court_london, _ly2_court_madrid, _ly2_court_sidney, _ly2_intro_screen, _ly2_player_selection

SECTION PAGE_70

ORG 0xC000

_ly2_court_london:
	binary "../build/layer2/court-london.bank_0.ly2.zx7"
	defw 0
	binary "../build/layer2/court-london.bank_1.ly2.zx7"
	defw 0
	binary "../build/layer2/court-london.bank_2.ly2.zx7"
	defw 0
	binary "../build/layer2/court-london.bank_3.ly2.zx7"
	defw 0
	binary "../build/layer2/court-london.bank_4.ly2.zx7"

SECTION PAGE_71

ORG 0xCFB1

_ly2_court_madrid:
	binary "../build/layer2/court-madrid.bank_0.ly2.zx7"
	defw 0
	binary "../build/layer2/court-madrid.bank_1.ly2.zx7"
	defw 0
	binary "../build/layer2/court-madrid.bank_2.ly2.zx7"
	defw 0
	binary "../build/layer2/court-madrid.bank_3.ly2.zx7"
	defw 0
	binary "../build/layer2/court-madrid.bank_4.ly2.zx7"

SECTION PAGE_72

ORG 0xDB12

_ly2_court_sidney:
	binary "../build/layer2/court-sidney.bank_0.ly2.zx7"
	defw 0
	binary "../build/layer2/court-sidney.bank_1.ly2.zx7"
	defw 0
	binary "../build/layer2/court-sidney.bank_2.ly2.zx7"
	defw 0
	binary "../build/layer2/court-sidney.bank_3.ly2.zx7"
	defw 0
	binary "../build/layer2/court-sidney.bank_4.ly2.zx7"

SECTION PAGE_74

ORG 0xC65B

_ly2_intro_screen:
	binary "../build/layer2/intro-screen.bank_0.ly2.zx7"
	defw 0
	binary "../build/layer2/intro-screen.bank_1.ly2.zx7"
	defw 0
	binary "../build/layer2/intro-screen.bank_2.ly2.zx7"
	defw 0
	binary "../build/layer2/intro-screen.bank_3.ly2.zx7"
	defw 0
	binary "../build/layer2/intro-screen.bank_4.ly2.zx7"

SECTION PAGE_76

ORG 0xCE8A

_ly2_player_selection:
	binary "../build/layer2/player-selection.bank_0.ly2.zx7"
	defw 0
	binary "../build/layer2/player-selection.bank_1.ly2.zx7"
	defw 0
	binary "../build/layer2/player-selection.bank_2.ly2.zx7"
	defw 0
	binary "../build/layer2/player-selection.bank_3.ly2.zx7"
	defw 0
	binary "../build/layer2/player-selection.bank_4.ly2.zx7"


; Last page used: 79
