// **** File generated by ase2next ***
// **** Do not edit ***

#include "skins.h"
#include "frames_def.h"

const SkinDefinition skin_ball_shadow = {
	.nSprites = 1,
	.maxPatterns = 1,
	.nFrames = 1,
	.frameAddresses = {
		{38, &sprite_ball_shadow},
	}
};

const SkinDefinition skin_ball = {
	.nSprites = 1,
	.maxPatterns = 1,
	.nFrames = 1,
	.frameAddresses = {
		{38, &sprite_ball},
	}
};

const SkinDefinition skin_net = {
	.nSprites = 22,
	.maxPatterns = 13,
	.nFrames = 1,
	.frameAddresses = {
		{38, &sprite_net},
	}
};

const SkinDefinition skin_player_back_a = {
	.nSprites = 8,
	.maxPatterns = 8,
	.nFrames = 21,
	.frameAddresses = {
		{38, &sprite_player_back_a_00},
		{38, &sprite_player_back_a_01},
		{39, &sprite_player_back_a_02},
		{39, &sprite_player_back_a_03},
		{39, &sprite_player_back_a_04},
		{39, &sprite_player_back_a_05},
		{39, &sprite_player_back_a_06},
		{40, &sprite_player_back_a_07},
		{40, &sprite_player_back_a_08},
		{40, &sprite_player_back_a_09},
		{40, &sprite_player_back_a_10},
		{41, &sprite_player_back_a_11},
		{40, &sprite_player_back_a_12},
		{41, &sprite_player_back_a_13},
		{41, &sprite_player_back_a_14},
		{41, &sprite_player_back_a_15},
		{42, &sprite_player_back_a_16},
		{42, &sprite_player_back_a_17},
		{42, &sprite_player_back_a_18},
		{42, &sprite_player_back_a_19},
		{42, &sprite_player_back_a_20},
	}
};

const SkinDefinition skin_umpire_head = {
	.nSprites = 1,
	.maxPatterns = 1,
	.nFrames = 4,
	.frameAddresses = {
		{38, &sprite_umpire_head_00},
		{38, &sprite_umpire_head_01},
		{38, &sprite_umpire_head_02},
		{38, &sprite_umpire_head_03},
	}
};

const SkinDefinition skin_player_front_a = {
	.nSprites = 8,
	.maxPatterns = 8,
	.nFrames = 21,
	.frameAddresses = {
		{43, &sprite_player_front_a_00},
		{41, &sprite_player_front_a_01},
		{43, &sprite_player_front_a_02},
		{43, &sprite_player_front_a_03},
		{43, &sprite_player_front_a_04},
		{44, &sprite_player_front_a_05},
		{44, &sprite_player_front_a_06},
		{44, &sprite_player_front_a_07},
		{44, &sprite_player_front_a_08},
		{45, &sprite_player_front_a_09},
		{45, &sprite_player_front_a_10},
		{43, &sprite_player_front_a_11},
		{45, &sprite_player_front_a_12},
		{45, &sprite_player_front_a_13},
		{45, &sprite_player_front_a_14},
		{46, &sprite_player_front_a_15},
		{46, &sprite_player_front_a_16},
		{46, &sprite_player_front_a_17},
		{46, &sprite_player_front_a_18},
		{46, &sprite_player_front_a_19},
		{47, &sprite_player_front_a_20},
	}
};

const SkinDefinition skin_umpire_chair = {
	.nSprites = 8,
	.maxPatterns = 8,
	.nFrames = 1,
	.frameAddresses = {
		{47, &sprite_umpire_chair},
	}
};

