// **** File generated by ase2next ***
// **** Do not edit ***

#ifndef _SKINS_H_
#define _SKINS_H_

#include "unified_sprites.h"

extern const SkinDefinition skin_ball_shadow;
extern const SkinDefinition skin_ball;
extern const SkinDefinition skin_net;
extern const SkinDefinition skin_player_back_a;
extern const SkinDefinition skin_player_front_a;
extern const SkinDefinition skin_umpire_chair;
extern const SkinDefinition skin_umpire_head;

#endif
