; File generated by sound_table.py
; Do not edit this file.

SECTION PAGE_100
	ORG $c000

PUBLIC _sounds_table

_sounds_table:
	defb 100
	defw sounds_out, 8697
	defb 101
	defw sounds_fault, 8001
	defb 102
	defw sounds_double_fault, 14336
	defb 103
	defw sounds_first_service, 16987
	defb 105
	defw sounds_second_service, 17546
	defb 108
	defw sounds_let, 7058
	defb 108
	defw sounds_touch, 9221
	defb 110
	defw sounds_game_point, 15012
	defb 111
	defw sounds_set_point, 16376
	defb 113
	defw sounds_match_point, 15273
	defb 115
	defw sounds_game_receiver, 16726
	defb 117
	defw sounds_game_server, 16726
	defb 119
	defw sounds_set_receiver, 16726
	defb 121
	defw sounds_set_server, 16726
	defb 123
	defw sounds_match_receiver, 16726
	defb 125
	defw sounds_match_server, 16726
	defb 127
	defw sounds_ball_bounce, 1215
	defb 128
	defw sounds_ball_hit, 4446
	defb 128
	defw sounds_ball_hit_2, 14336
	defb 130
	defw sounds_net, 11146
	defb 131
	defw sounds_score_0_15, 18008
	defb 133
	defw sounds_score_0_30, 19165
	defb 136
	defw sounds_score_0_40, 19441
	defb 138
	defw sounds_score_15_0, 14408
	defb 140
	defw sounds_score_15_15, 17843
	defb 142
	defw sounds_score_15_30, 17901
	defb 144
	defw sounds_score_15_40, 19904
	defb 147
	defw sounds_score_30_0, 14131
	defb 148
	defw sounds_score_30_15, 20736
	defb 151
	defw sounds_score_30_30, 20709
	defb 154
	defw sounds_score_30_40, 21371
	defb 156
	defw sounds_score_40_0, 17679
	defb 158
	defw sounds_score_40_15, 21903
	defb 161
	defw sounds_score_40_30, 19871
	defb 163
	defw sounds_deuce, 10015
	defb 165
	defw sounds_ad_receiver, 18675
	defb 167
	defw sounds_ad_server, 16338
	defb 169
	defw sounds_umpf_diego_1, 10504
	defb 170
	defw sounds_umpf_diego_2, 8409
	defb 171
	defw sounds_umpf_victor_1, 11564
	defb 173
	defw sounds_umpf_victor_2, 11337
	defb 174
	defw sounds_crowd_clapping, 59392
	defb 181
	defw sounds_touch_hit_male, 13748

sounds_out:
	binary "../build/sounds/out_page_100.bin"

SECTION PAGE_101
	ORG $c000

	binary "../build/sounds/out_page_101.bin"

sounds_fault:
	binary "../build/sounds/fault_page_101.bin"

SECTION PAGE_102
	ORG $c000

	binary "../build/sounds/fault_page_102.bin"

sounds_double_fault:
	binary "../build/sounds/double_fault_page_102.bin"

SECTION PAGE_103
	ORG $c000

	binary "../build/sounds/double_fault_page_103.bin"

sounds_first_service:
	binary "../build/sounds/first_service_page_103.bin"

SECTION PAGE_104
	ORG $c000

	binary "../build/sounds/first_service_page_104.bin"

SECTION PAGE_105
	ORG $c000

	binary "../build/sounds/first_service_page_105.bin"

sounds_second_service:
	binary "../build/sounds/second_service_page_105.bin"

SECTION PAGE_106
	ORG $c000

	binary "../build/sounds/second_service_page_106.bin"

SECTION PAGE_107
	ORG $c000

	binary "../build/sounds/second_service_page_107.bin"

SECTION PAGE_108
	ORG $c000

	binary "../build/sounds/second_service_page_108.bin"

sounds_let:
	binary "../build/sounds/let_page_108.bin"

sounds_touch:
	binary "../build/sounds/touch_page_108.bin"

SECTION PAGE_109
	ORG $c000

	binary "../build/sounds/touch_page_109.bin"

SECTION PAGE_110
	ORG $c000

	binary "../build/sounds/touch_page_110.bin"

sounds_game_point:
	binary "../build/sounds/game_point_page_110.bin"

SECTION PAGE_111
	ORG $c000

	binary "../build/sounds/game_point_page_111.bin"

sounds_set_point:
	binary "../build/sounds/set_point_page_111.bin"

SECTION PAGE_112
	ORG $c000

	binary "../build/sounds/set_point_page_112.bin"

SECTION PAGE_113
	ORG $c000

	binary "../build/sounds/set_point_page_113.bin"

sounds_match_point:
	binary "../build/sounds/match_point_page_113.bin"

SECTION PAGE_114
	ORG $c000

	binary "../build/sounds/match_point_page_114.bin"

SECTION PAGE_115
	ORG $c000

	binary "../build/sounds/match_point_page_115.bin"

sounds_game_receiver:
	binary "../build/sounds/game_receiver_page_115.bin"

SECTION PAGE_116
	ORG $c000

	binary "../build/sounds/game_receiver_page_116.bin"

SECTION PAGE_117
	ORG $c000

	binary "../build/sounds/game_receiver_page_117.bin"

sounds_game_server:
	binary "../build/sounds/game_server_page_117.bin"

SECTION PAGE_118
	ORG $c000

	binary "../build/sounds/game_server_page_118.bin"

SECTION PAGE_119
	ORG $c000

	binary "../build/sounds/game_server_page_119.bin"

sounds_set_receiver:
	binary "../build/sounds/set_receiver_page_119.bin"

SECTION PAGE_120
	ORG $c000

	binary "../build/sounds/set_receiver_page_120.bin"

SECTION PAGE_121
	ORG $c000

	binary "../build/sounds/set_receiver_page_121.bin"

sounds_set_server:
	binary "../build/sounds/set_server_page_121.bin"

SECTION PAGE_122
	ORG $c000

	binary "../build/sounds/set_server_page_122.bin"

SECTION PAGE_123
	ORG $c000

	binary "../build/sounds/set_server_page_123.bin"

sounds_match_receiver:
	binary "../build/sounds/match_receiver_page_123.bin"

SECTION PAGE_124
	ORG $c000

	binary "../build/sounds/match_receiver_page_124.bin"

SECTION PAGE_125
	ORG $c000

	binary "../build/sounds/match_receiver_page_125.bin"

sounds_match_server:
	binary "../build/sounds/match_server_page_125.bin"

SECTION PAGE_126
	ORG $c000

	binary "../build/sounds/match_server_page_126.bin"

SECTION PAGE_127
	ORG $c000

	binary "../build/sounds/match_server_page_127.bin"

sounds_ball_bounce:
	binary "../build/sounds/ball_bounce_page_127.bin"

SECTION PAGE_128
	ORG $c000

	binary "../build/sounds/ball_bounce_page_128.bin"

sounds_ball_hit:
	binary "../build/sounds/ball_hit_page_128.bin"

sounds_ball_hit_2:
	binary "../build/sounds/ball_hit_2_page_128.bin"

SECTION PAGE_129
	ORG $c000

	binary "../build/sounds/ball_hit_2_page_129.bin"

SECTION PAGE_130
	ORG $c000

	binary "../build/sounds/ball_hit_2_page_130.bin"

sounds_net:
	binary "../build/sounds/net_page_130.bin"

SECTION PAGE_131
	ORG $c000

	binary "../build/sounds/net_page_131.bin"

sounds_score_0_15:
	binary "../build/sounds/score_0_15_page_131.bin"

SECTION PAGE_132
	ORG $c000

	binary "../build/sounds/score_0_15_page_132.bin"

SECTION PAGE_133
	ORG $c000

	binary "../build/sounds/score_0_15_page_133.bin"

sounds_score_0_30:
	binary "../build/sounds/score_0_30_page_133.bin"

SECTION PAGE_134
	ORG $c000

	binary "../build/sounds/score_0_30_page_134.bin"

SECTION PAGE_135
	ORG $c000

	binary "../build/sounds/score_0_30_page_135.bin"

SECTION PAGE_136
	ORG $c000

	binary "../build/sounds/score_0_30_page_136.bin"

sounds_score_0_40:
	binary "../build/sounds/score_0_40_page_136.bin"

SECTION PAGE_137
	ORG $c000

	binary "../build/sounds/score_0_40_page_137.bin"

SECTION PAGE_138
	ORG $c000

	binary "../build/sounds/score_0_40_page_138.bin"

sounds_score_15_0:
	binary "../build/sounds/score_15_0_page_138.bin"

SECTION PAGE_139
	ORG $c000

	binary "../build/sounds/score_15_0_page_139.bin"

SECTION PAGE_140
	ORG $c000

	binary "../build/sounds/score_15_0_page_140.bin"

sounds_score_15_15:
	binary "../build/sounds/score_15_15_page_140.bin"

SECTION PAGE_141
	ORG $c000

	binary "../build/sounds/score_15_15_page_141.bin"

SECTION PAGE_142
	ORG $c000

	binary "../build/sounds/score_15_15_page_142.bin"

sounds_score_15_30:
	binary "../build/sounds/score_15_30_page_142.bin"

SECTION PAGE_143
	ORG $c000

	binary "../build/sounds/score_15_30_page_143.bin"

SECTION PAGE_144
	ORG $c000

	binary "../build/sounds/score_15_30_page_144.bin"

sounds_score_15_40:
	binary "../build/sounds/score_15_40_page_144.bin"

SECTION PAGE_145
	ORG $c000

	binary "../build/sounds/score_15_40_page_145.bin"

SECTION PAGE_146
	ORG $c000

	binary "../build/sounds/score_15_40_page_146.bin"

SECTION PAGE_147
	ORG $c000

	binary "../build/sounds/score_15_40_page_147.bin"

sounds_score_30_0:
	binary "../build/sounds/score_30_0_page_147.bin"

SECTION PAGE_148
	ORG $c000

	binary "../build/sounds/score_30_0_page_148.bin"

sounds_score_30_15:
	binary "../build/sounds/score_30_15_page_148.bin"

SECTION PAGE_149
	ORG $c000

	binary "../build/sounds/score_30_15_page_149.bin"

SECTION PAGE_150
	ORG $c000

	binary "../build/sounds/score_30_15_page_150.bin"

SECTION PAGE_151
	ORG $c000

	binary "../build/sounds/score_30_15_page_151.bin"

sounds_score_30_30:
	binary "../build/sounds/score_30_30_page_151.bin"

SECTION PAGE_152
	ORG $c000

	binary "../build/sounds/score_30_30_page_152.bin"

SECTION PAGE_153
	ORG $c000

	binary "../build/sounds/score_30_30_page_153.bin"

SECTION PAGE_154
	ORG $c000

	binary "../build/sounds/score_30_30_page_154.bin"

sounds_score_30_40:
	binary "../build/sounds/score_30_40_page_154.bin"

SECTION PAGE_155
	ORG $c000

	binary "../build/sounds/score_30_40_page_155.bin"

SECTION PAGE_156
	ORG $c000

	binary "../build/sounds/score_30_40_page_156.bin"

sounds_score_40_0:
	binary "../build/sounds/score_40_0_page_156.bin"

SECTION PAGE_157
	ORG $c000

	binary "../build/sounds/score_40_0_page_157.bin"

SECTION PAGE_158
	ORG $c000

	binary "../build/sounds/score_40_0_page_158.bin"

sounds_score_40_15:
	binary "../build/sounds/score_40_15_page_158.bin"

SECTION PAGE_159
	ORG $c000

	binary "../build/sounds/score_40_15_page_159.bin"

SECTION PAGE_160
	ORG $c000

	binary "../build/sounds/score_40_15_page_160.bin"

SECTION PAGE_161
	ORG $c000

	binary "../build/sounds/score_40_15_page_161.bin"

sounds_score_40_30:
	binary "../build/sounds/score_40_30_page_161.bin"

SECTION PAGE_162
	ORG $c000

	binary "../build/sounds/score_40_30_page_162.bin"

SECTION PAGE_163
	ORG $c000

	binary "../build/sounds/score_40_30_page_163.bin"

sounds_deuce:
	binary "../build/sounds/deuce_page_163.bin"

SECTION PAGE_164
	ORG $c000

	binary "../build/sounds/deuce_page_164.bin"

SECTION PAGE_165
	ORG $c000

	binary "../build/sounds/deuce_page_165.bin"

sounds_ad_receiver:
	binary "../build/sounds/ad_receiver_page_165.bin"

SECTION PAGE_166
	ORG $c000

	binary "../build/sounds/ad_receiver_page_166.bin"

SECTION PAGE_167
	ORG $c000

	binary "../build/sounds/ad_receiver_page_167.bin"

sounds_ad_server:
	binary "../build/sounds/ad_server_page_167.bin"

SECTION PAGE_168
	ORG $c000

	binary "../build/sounds/ad_server_page_168.bin"

SECTION PAGE_169
	ORG $c000

	binary "../build/sounds/ad_server_page_169.bin"

sounds_umpf_diego_1:
	binary "../build/sounds/umpf_diego_1_page_169.bin"

SECTION PAGE_170
	ORG $c000

	binary "../build/sounds/umpf_diego_1_page_170.bin"

sounds_umpf_diego_2:
	binary "../build/sounds/umpf_diego_2_page_170.bin"

SECTION PAGE_171
	ORG $c000

	binary "../build/sounds/umpf_diego_2_page_171.bin"

sounds_umpf_victor_1:
	binary "../build/sounds/umpf_victor_1_page_171.bin"

SECTION PAGE_172
	ORG $c000

	binary "../build/sounds/umpf_victor_1_page_172.bin"

SECTION PAGE_173
	ORG $c000

	binary "../build/sounds/umpf_victor_1_page_173.bin"

sounds_umpf_victor_2:
	binary "../build/sounds/umpf_victor_2_page_173.bin"

SECTION PAGE_174
	ORG $c000

	binary "../build/sounds/umpf_victor_2_page_174.bin"

sounds_crowd_clapping:
	binary "../build/sounds/crowd_clapping_page_174.bin"

SECTION PAGE_175
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_175.bin"

SECTION PAGE_176
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_176.bin"

SECTION PAGE_177
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_177.bin"

SECTION PAGE_178
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_178.bin"

SECTION PAGE_179
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_179.bin"

SECTION PAGE_180
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_180.bin"

SECTION PAGE_181
	ORG $c000

	binary "../build/sounds/crowd_clapping_page_181.bin"

sounds_touch_hit_male:
	binary "../build/sounds/touch_hit_male_page_181.bin"

SECTION PAGE_182
	ORG $c000

	binary "../build/sounds/touch_hit_male_page_182.bin"

SECTION PAGE_183
	ORG $c000

	binary "../build/sounds/touch_hit_male_page_183.bin"

